#cloud-config
users:
  - name: exporter
    uid: 2000
write_files:
  - path: /etc/systemd/system/exporter.service
    permissions: 0644
    owner: root:root
    content: |
      [Unit]
      Wants=network-online.target docker.socket
      After=network-online.target docker.socket

      [Service]
      TimeoutStartSec=0
      ExecStart=/usr/bin/docker run --rm -u 2000 \
          --name=exporter \
          --net=host \
          --volume=/run/docker.sock:/run/docker.sock \
          prometheuscommunity/stackdriver-exporter:latest \
              --monitoring.metrics-type-prefixes "compute.googleapis.com/guest/cpu/"

      ExecReload=/usr/bin/docker restart exporter
      ExecStop=/usr/bin/docker stop exporter
      ExecStopPost=/usr/bin/docker rm exporter

runcmd:
  - systemctl daemon-reload
  - systemctl enable exporter.service
  - systemctl start exporter.service
  
